// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPxuYZ9PY5BqiZQ0TOcO7aWvYZyjP_xB8',
    appId: '1:235756938742:web:fcb190da9888a4a13093d7',
    messagingSenderId: '235756938742',
    projectId: 'fansideapp',
    authDomain: 'fansideapp.firebaseapp.com',
    storageBucket: 'fansideapp.firebasestorage.app',
    measurementId: 'G-8HBFGESF6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9H4lfBkKzaCj9-S9hk_vKwWohrlMh0E',
    appId: '1:235756938742:android:d4d732775ad17fb03093d7',
    messagingSenderId: '235756938742',
    projectId: 'fansideapp',
    storageBucket: 'fansideapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiD_ZT84WuhPOGKvyjzJqkIdN0uBBZKZ0',
    appId: '1:235756938742:ios:47b5170fab49950e3093d7',
    messagingSenderId: '235756938742',
    projectId: 'fansideapp',
    storageBucket: 'fansideapp.firebasestorage.app',
    iosBundleId: 'com.example.fansideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiD_ZT84WuhPOGKvyjzJqkIdN0uBBZKZ0',
    appId: '1:235756938742:ios:47b5170fab49950e3093d7',
    messagingSenderId: '235756938742',
    projectId: 'fansideapp',
    storageBucket: 'fansideapp.firebasestorage.app',
    iosBundleId: 'com.example.fansideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPxuYZ9PY5BqiZQ0TOcO7aWvYZyjP_xB8',
    appId: '1:235756938742:web:66c494f7490656a43093d7',
    messagingSenderId: '235756938742',
    projectId: 'fansideapp',
    authDomain: 'fansideapp.firebaseapp.com',
    storageBucket: 'fansideapp.firebasestorage.app',
    measurementId: 'G-SBNL7E0Q77',
  );
}
